[package]
name = "maid"
version = "0.1.0"
edition = "2021"

[lib]
name = "maid"
path = "src/lib.rs"

[[bin]]
name = "maid-bot"
path = "bin/main.rs"

[workspace]
members = ["crates/*"]

[workspace.dependencies]
tokio = "1.26.0"
reqwest = "0.11.14"
async-trait = "0.1.66"
derive_more = { version = "0.99.17", features = [
    "display",
], default-features = false }
thiserror = "1.0.39"
serde_json = "1.0.94"

[dependencies]
tokio.workspace = true
