[package]
name = "llam-engine"
version = "0.1.0"
edition = "2021"

[dependencies]
serde.workspace = true
derive_more.workspace = true
thiserror.workspace = true
reqwest.workspace = true
async-trait.workspace = true
serde_json.workspace = true
