[rt]
threads = 4

[bot.telegram]
token = "5678067454:AAFW-5gx2dzbJZbVrnpFfyVoQEKjr1UL4bw"

[bot.vkontakte]
token = "vk1.a.MhDISCeKcVDMhRBF8Y1yf-3yp85XT4F5vZ6r3NJXWXW5jlzk33JODNLSyTfhI0y8nPZGvxMXijCteAQEKv7JsQe3YeIKbAwO1xJgm6dBM-QQ2DibfJuUbh6cNR8_JyX2_uoI1w2z67---MUlAsuzK8TApTucD3zLZeevHHckvNIih5untF2_u-rrOJkzJ4OE4fJMEhDc9-h60cv-1wCaAA"

[ai]
temperature = 0.5

[ai.lam_backend.openai]
model = "gpt-3.5-turbo"
token = "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"
